version: 33
# JinGo VPN Multi-Platform Build Configuration
# Updated: 2026-02-02
#
# 所有任务均为手动触发，需要指定 brand 参数
# brand 参数: 白标品牌 ID (数字，1=JinGo 默认品牌，2-100=自定义品牌)
#
# 白标目录结构: white-labeling/<brand_id>/
#   - bundle_config.json: 品牌配置
#   - icons/: 品牌图标资源
#
# 并行构建: 手动同时触发多个平台任务即可实现并行
# - 不同 executor 的任务可以并行运行
# - 同一 executor 的任务会排队

jobs:
  # ==========================================================================
  # macOS 构建任务
  # ==========================================================================
  - name: Build macOS
    jobExecutor: macos-builder
    steps:
      - !CheckoutStep
        name: Checkout
        cloneCredential: !DefaultCredential {}
        withLfs: false
        withSubmodules: true
        condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL

      - !CommandStep
        name: Verify Dependencies
        runInContainer: false
        interpreter: !DefaultInterpreter
          commands: |
            export HOME="${HOME:-/var/root}"
            export PATH="/opt/homebrew/bin:/usr/local/bin:$PATH"

            echo "=== Verifying Dependencies ==="
            echo "Brand ID: @param:brand@"

            # 检查 JinDoCore XCFramework
            XCFW="third_party/jindo/apple/JinDoCore.xcframework"
            if [ -d "$XCFW" ]; then
                echo "[OK] Found JinDoCore.xcframework"
            else
                echo "[ERROR] JinDoCore.xcframework not found: $XCFW"
                exit 1
            fi

            # 检查白标目录
            BRAND_DIR="white-labeling/@param:brand@"
            if [ -d "$BRAND_DIR" ]; then
                echo "[OK] Found white-label directory: $BRAND_DIR"
                [ -f "$BRAND_DIR/bundle_config.json" ] && echo "[OK] Found bundle_config.json" || echo "[WARNING] bundle_config.json not found"
                [ -d "$BRAND_DIR/icons/" ] && echo "[OK] Found icons directory" || echo "[WARNING] icons directory not found"
            else
                echo "[ERROR] White-label directory not found: $BRAND_DIR"
                exit 1
            fi

            echo ""
            echo "Dependencies verified"
        condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL

      - !CommandStep
        name: Build Release
        runInContainer: false
        interpreter: !DefaultInterpreter
          commands: |
            export HOME="${HOME:-/var/root}"
            export PATH="/opt/homebrew/bin:/usr/local/bin:$PATH"
            export DEVELOPER_DIR="/Volumes/mindata/Xcode.app/Contents/Developer"
            export QT_MACOS_PATH="/Volumes/mindata/Qt/6.10.1/macos"
            export PATH="$QT_MACOS_PATH/bin:$PATH"
            export BRAND="@param:brand@"
            export ENABLE_LICENSE_CHECK=ON
            export ENABLE_CONFIG_SIGNATURE_VERIFY=ON

            # 从 bundle_config.json 读取 Bundle ID
            BRAND_JSON="white-labeling/@param:brand@/bundle_config.json"
            if [ -f "$BRAND_JSON" ]; then
              BUNDLE_ID=$(python3 -c "import json; d=json.load(open('$BRAND_JSON')); c=d.get('config',d); print(c.get('bundleId',{}).get('macos','') or c.get('bundleId',''))" 2>/dev/null || echo "")
            fi

            if [ -n "$BUNDLE_ID" ]; then
              echo "Bundle ID: $BUNDLE_ID"
              ./scripts/build/build-macos.sh --clean --release --dmg --skip-sign --bundle-id "$BUNDLE_ID"
            else
              ./scripts/build/build-macos.sh --clean --release --dmg --skip-sign
            fi
        condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL

      - !PublishArtifactStep
        name: Publish Artifacts
        artifacts: release/**
        condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL

    paramSpecs:
      - !TextParam
        name: brand
        description: White-label brand ID (1=JinGo, 2-100=custom brands)
        defaultValueProvider: !SpecifiedDefaultValue
          value: '1'

    retryCondition: never
    maxRetries: 0
    timeout: 3600

  # ==========================================================================
  # iOS 构建任务
  # ==========================================================================
  - name: Build iOS
    jobExecutor: macos-builder
    steps:
      - !CheckoutStep
        name: Checkout
        cloneCredential: !DefaultCredential {}
        withLfs: false
        withSubmodules: true
        condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL

      - !CommandStep
        name: Verify Dependencies
        runInContainer: false
        interpreter: !DefaultInterpreter
          commands: |
            export HOME="${HOME:-/var/root}"
            export PATH="/opt/homebrew/bin:/usr/local/bin:$PATH"

            echo "=== Verifying Dependencies ==="
            echo "Brand ID: @param:brand@"

            # 检查 JinDoCore XCFramework
            XCFW="third_party/jindo/apple/JinDoCore.xcframework"
            if [ -d "$XCFW" ]; then
                echo "[OK] Found JinDoCore.xcframework"
            else
                echo "[ERROR] JinDoCore.xcframework not found: $XCFW"
                exit 1
            fi

            # 检查白标目录
            BRAND_DIR="white-labeling/@param:brand@"
            if [ -d "$BRAND_DIR" ]; then
                echo "[OK] Found white-label directory: $BRAND_DIR"
                [ -f "$BRAND_DIR/bundle_config.json" ] && echo "[OK] Found bundle_config.json" || echo "[WARNING] bundle_config.json not found"
                [ -d "$BRAND_DIR/icons/" ] && echo "[OK] Found icons directory" || echo "[WARNING] icons directory not found"
            else
                echo "[ERROR] White-label directory not found: $BRAND_DIR"
                exit 1
            fi

            echo ""
            echo "Dependencies verified"
        condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL

      - !CommandStep
        name: Build Release
        runInContainer: false
        interpreter: !DefaultInterpreter
          commands: |
            export HOME="${HOME:-/var/root}"
            export PATH="/opt/homebrew/bin:/usr/local/bin:$PATH"
            export DEVELOPER_DIR="/Volumes/mindata/Xcode.app/Contents/Developer"
            export QT_IOS_PATH="/Volumes/mindata/Qt/6.10.1/ios"
            export BRAND="@param:brand@"
            export ENABLE_LICENSE_CHECK=ON
            export ENABLE_CONFIG_SIGNATURE_VERIFY=ON

            # 从 bundle_config.json 读取 Bundle ID
            BRAND_JSON="white-labeling/@param:brand@/bundle_config.json"
            BUILD_ARGS="--clean --release --skip-sign"
            if [ -f "$BRAND_JSON" ]; then
              BUNDLE_ID=$(python3 -c "import json; d=json.load(open('$BRAND_JSON')); c=d.get('config',d); print(c.get('bundleId',{}).get('ios','') or c.get('bundleId',''))" 2>/dev/null || echo "")
              if [ -n "$BUNDLE_ID" ]; then
                echo "Bundle ID: $BUNDLE_ID"
                BUILD_ARGS="$BUILD_ARGS --bundle-id $BUNDLE_ID"
              fi
            fi

            eval ./scripts/build/build-ios.sh $BUILD_ARGS
        condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL

      - !PublishArtifactStep
        name: Publish Artifacts
        artifacts: release/**
        condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL

    paramSpecs:
      - !TextParam
        name: brand
        description: White-label brand ID (1=JinGo, 2-100=custom brands)
        defaultValueProvider: !SpecifiedDefaultValue
          value: '1'

    retryCondition: never
    maxRetries: 0
    timeout: 3600

  # ==========================================================================
  # Android 构建任务
  # ==========================================================================
  - name: Build Android
    jobExecutor: linux-builder
    steps:
      - !CheckoutStep
        name: Checkout
        cloneCredential: !DefaultCredential {}
        withLfs: false
        withSubmodules: true
        condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL

      - !CommandStep
        name: Verify Dependencies
        runInContainer: false
        interpreter: !DefaultInterpreter
          commands: |
            echo "=== Verifying Dependencies ==="
            echo "Brand ID: @param:brand@"

            HAS_ERROR=false

            # 检查默认 ABI (arm64-v8a) 的 JinDoCore 和 SuperRay
            ABI="arm64-v8a"
            LIB="third_party/jindo/android/${ABI}/libJinDoCore.a"
            if [ -f "$LIB" ]; then
                echo "[OK] Found libJinDoCore.a for ${ABI}"
            else
                echo "[ERROR] libJinDoCore.a not found for ${ABI}"
                HAS_ERROR=true
            fi

            SO="third_party/jindo/android/${ABI}/libsuperray.so"
            if [ -f "$SO" ]; then
                echo "[OK] Found libsuperray.so for ${ABI}"
            else
                echo "[ERROR] libsuperray.so not found for ${ABI}"
                HAS_ERROR=true
            fi

            # 检查头文件和 JNI 源文件
            [ -f "third_party/jindo/android/include/superray.h" ] && echo "[OK] Found superray.h" || echo "[WARNING] superray.h not found"
            [ -f "third_party/jindo/android/jni/tun2socks_jni.cpp" ] && echo "[OK] Found JNI source files" || echo "[WARNING] JNI source files not found"

            # 检查白标目录
            BRAND_DIR="white-labeling/@param:brand@"
            if [ -d "$BRAND_DIR" ]; then
                echo "[OK] Found white-label directory: $BRAND_DIR"
                [ -f "$BRAND_DIR/bundle_config.json" ] && echo "[OK] Found bundle_config.json" || echo "[WARNING] bundle_config.json not found"
            else
                echo "[ERROR] White-label directory not found: $BRAND_DIR"
                HAS_ERROR=true
            fi

            if [ "$HAS_ERROR" = true ]; then
                echo ""
                echo "[FAILED] Missing required dependencies"
                exit 1
            fi

            echo ""
            echo "Dependencies verified"
        condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL

      - !CommandStep
        name: Build Release
        runInContainer: false
        interpreter: !DefaultInterpreter
          commands: |
            export QT_BASE_PATH="/mnt/dev/Qt/6.10.1"
            export QT_HOST_PATH="/mnt/dev/Qt/6.10.1/gcc_64"
            export ANDROID_SDK_ROOT="/mnt/dev/Android/Sdk"
            export ANDROID_NDK="$ANDROID_SDK_ROOT/ndk/29.0.14206865"
            export JAVA_HOME="/usr/lib/jvm/java-21-openjdk-amd64"
            export PATH="$JAVA_HOME/bin:$PATH"
            export BRAND="@param:brand@"
            export ENABLE_LICENSE_CHECK=ON
            export ENABLE_CONFIG_SIGNATURE_VERIFY=ON

            ./scripts/build/build-android.sh --clean --release
        condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL

      - !PublishArtifactStep
        name: Publish Artifacts
        artifacts: release/**
        condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL

    paramSpecs:
      - !TextParam
        name: brand
        description: White-label brand ID (1=JinGo, 2-100=custom brands)
        defaultValueProvider: !SpecifiedDefaultValue
          value: '1'

    retryCondition: never
    maxRetries: 0
    timeout: 3600

  # ==========================================================================
  # Linux 构建任务
  # ==========================================================================
  - name: Build Linux
    jobExecutor: linux-builder
    steps:
      - !CheckoutStep
        name: Checkout
        cloneCredential: !DefaultCredential {}
        withLfs: false
        withSubmodules: true
        condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL

      - !CommandStep
        name: Verify Dependencies
        runInContainer: false
        interpreter: !DefaultInterpreter
          commands: |
            echo "=== Verifying Dependencies ==="
            echo "Brand ID: @param:brand@"

            # 检查 JinDoCore 静态库
            if [ -f "third_party/jindo/linux/x64/libJinDoCore.a" ]; then
                echo "[OK] Found libJinDoCore.a"
            else
                echo "[ERROR] libJinDoCore.a not found in third_party/jindo/linux/x64/"
                exit 1
            fi

            [ -f "third_party/jindo/linux/x64/include/superray.h" ] && echo "[OK] Found superray.h" || echo "[WARNING] superray.h not found"

            # 检查白标目录
            BRAND_DIR="white-labeling/@param:brand@"
            if [ -d "$BRAND_DIR" ]; then
                echo "[OK] Found white-label directory: $BRAND_DIR"
                [ -f "$BRAND_DIR/bundle_config.json" ] && echo "[OK] Found bundle_config.json" || echo "[WARNING] bundle_config.json not found"
            else
                echo "[ERROR] White-label directory not found: $BRAND_DIR"
                exit 1
            fi

            echo ""
            echo "Dependencies verified"
        condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL

      - !CommandStep
        name: Build Release
        runInContainer: false
        interpreter: !DefaultInterpreter
          commands: |
            export Qt6_DIR="/mnt/dev/Qt/6.10.1/gcc_64"
            export PATH="$Qt6_DIR/bin:$PATH"
            export BRAND="@param:brand@"
            export ENABLE_LICENSE_CHECK=ON
            export ENABLE_CONFIG_SIGNATURE_VERIFY=ON

            ./scripts/build/build-linux.sh --clean --release --deploy --package
        condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL

      - !PublishArtifactStep
        name: Publish Artifacts
        artifacts: release/**
        condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL

    paramSpecs:
      - !TextParam
        name: brand
        description: White-label brand ID (1=JinGo, 2-100=custom brands)
        defaultValueProvider: !SpecifiedDefaultValue
          value: '1'

    retryCondition: never
    maxRetries: 0
    timeout: 3600

  # ==========================================================================
  # Windows 构建任务
  # ==========================================================================
  - name: Build Windows
    jobExecutor: windows-builder
    steps:
      - !CheckoutStep
        name: Checkout
        cloneCredential: !DefaultCredential {}
        withLfs: false
        withSubmodules: true
        condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL

      - !CommandStep
        name: Verify Dependencies
        runInContainer: false
        interpreter: !DefaultInterpreter
          commands: |
            echo === Verifying Dependencies ===
            echo Brand ID: @param:brand@

            REM 检查 JinDoCore 静态库
            if exist "third_party\jindo\windows\mingw64\libJinDoCore.a" (
                echo [OK] Found libJinDoCore.a
            ) else (
                echo [ERROR] libJinDoCore.a not found
                exit /b 1
            )

            REM 检查 superray.h
            if exist "third_party\jindo\windows\mingw64\include\superray.h" (
                echo [OK] Found superray.h
            ) else (
                echo [WARNING] superray.h not found
            )

            REM 检查白标目录
            set BRAND_DIR=white-labeling\@param:brand@
            if exist "%BRAND_DIR%" (
                echo [OK] Found white-label directory: %BRAND_DIR%
                if exist "%BRAND_DIR%\bundle_config.json" (
                    echo [OK] Found bundle_config.json
                ) else (
                    echo [WARNING] bundle_config.json not found
                )
            ) else (
                echo [ERROR] White-label directory not found: %BRAND_DIR%
                exit /b 1
            )

            echo.
            echo Dependencies verified
        condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL

      - !CommandStep
        name: Build Release
        runInContainer: false
        interpreter: !DefaultInterpreter
          commands: |
            set MSYS2_ROOT=D:\msys64
            set BASH_EXE=%MSYS2_ROOT%\usr\bin\bash.exe

            if not exist "%BASH_EXE%" (
                echo [ERROR] MSYS2 bash not found: %BASH_EXE%
                exit /b 1
            )

            "%BASH_EXE%" --login -c "cd '%CD%' && export BRAND=@param:brand@ && export ENABLE_LICENSE_CHECK=ON && export ENABLE_CONFIG_SIGNATURE_VERIFY=ON && bash scripts/build/build-windows.sh clean"

            if errorlevel 1 (
                echo [ERROR] JinGo build failed
                exit /b 1
            )
        condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL

      - !PublishArtifactStep
        name: Publish Artifacts
        artifacts: release/**
        condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL

    paramSpecs:
      - !TextParam
        name: brand
        description: White-label brand ID (1=JinGo, 2-100=custom brands)
        defaultValueProvider: !SpecifiedDefaultValue
          value: '1'

    retryCondition: never
    maxRetries: 0
    timeout: 3600
